export const skillIdMap = {
  acrobatics: "acrobatics",
  animal_handling: "animalHandling",
  animalHandling: "animalHandling",
  arcana: "arcana",
  athletics: "athletics",
  deception: "deception",
  history: "history",
  insight: "insight",
  intimidation: "intimidation",
  investigation: "investigation",
  medicine: "medicine",
  nature: "nature",
  perception: "perception",
  performance: "performance",
  persuasion: "persuasion",
  religion: "religion",
  sleight_of_hand: "sleightOfHand",
  sleightOfHand: "sleightOfHand",
  stealth: "stealth",
  survival: "survival",
};
